sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    notes: '[便笺](/notes/)'
    more: '[更多](/about/)'
  widgets:
    # Recent update
    recent:
      rss: /atom.xml # npm i hexo-generator-feed

article:
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
    '设计开发': '#03a9f4'
    # '奇思妙想': '#009688'
    'web3': '#ff9800'
    '技术加油站': '#4caf50'
    '开源库': '#4caf50'
    '博客主题': '#ffa000'
    # '应用程序': '#e91e63'
    # '实用脚本': '#009688'
  share: [wechat, weibo, email, link]
  related_posts:
    enable: false
    auto_cover: true

comments:
  service: beaudar
  beaudar:
    repo: Frederick-X/x.wwweb3.net

footer:
  social:
    github:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/Frederick-X
    music:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
      url: https://music.163.com/#/user/home?id=63035382
    unsplash:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
      url: https://unsplash.com/@xaoxuu
    comments:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments
  sitemap:
    '博客':
      - '[近期](/)'
      - '[分类](/blog/categories/)'
      - '[标签](/blog/tags/)'
      - '[归档](/blog/archives/)'
    '项目':
      - '[开源库](/wiki/tags/开源库/)'
      - '[实用脚本](/wiki/tags/实用脚本/)'
      - '[博客主题](/wiki/tags/博客主题/)'
      - '[应用程序](/wiki/tags/应用程序/)'
    '社交':
      - '[友链](/friends/)'
      - '[留言板](/about/#comments)'
    '更多':
      - '[关于本站](/about/)'
      - '[GitHub](https://github.com/xaoxuu)'
      - '[GitLab](http://42.192.89.158:8099/explore)'
  source: '[GitHub](https://github.com/xaoxuu/xaoxuu.github.io/)'


style:
  codeblock:
    scrollbar: 0px

######## JS Plugins ########
plugins:
  ## required plugins ##
  # jquery
  jquery: https://fastly.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js

  # issues api
  sitesjs: /js/plugins/sites.js
  friendsjs: /js/plugins/friends.js

  ## optional plugins ##
  # preload
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: https://fastly.jsdelivr.net/gh/volantis-x/cdn-volantis@4.1.2/js/instant_page.js
    flying_pages: https://fastly.jsdelivr.net/gh/gijo-varghese/flying-pages@2.1.2/flying-pages.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://fastly.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: #true
    js: https://fastly.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: true
    js: https://fastly.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    css: https://fastly.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    # 使用waline评论可以写: #waline_container .vcontent img
    selector: .swiper-slide img # 多个选择器用英文逗号隔开

  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper@6/swiper-bundle.min.css
    js: https://unpkg.com/swiper@6/swiper-bundle.min.js


  # 赫蹏 (Heti) - 专为中文网页内容设计的排版样式增强
  # https://github.com/sivan/heti
  heti:
    enable: false
    css: https://unpkg.com/heti/umd/heti.min.css
    js: https://unpkg.com/heti/umd/heti-addon.min.js

  # MathJax
  # 需在Markdown文件开头加入mathjax: true
  # 推荐使用Pandoc: npm uninstall hexo-renderer-marked --save & npm install hexo-renderer-pandoc --save
  mathjax:
    enable: false
    cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML

  # Katex - The fastest math typesetting library for the web
  # https://katex.org/docs/autorender.html
  # https://github.com/KaTeX/KaTeX
  # 使用 hexo-renderer-markdown-it-plus 作为公式渲染器：npm uninstall hexo-renderer-marked --save npm install hexo-renderer-markdown-it-plus --save
  katex:
    enable: false
    min_css: <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    min_js: <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    auto_render_min_js: <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"onload="renderMathInElement(document.body);"></script>
